PATH=$HOME/bin:$PATH
C_INCLUDE_PATH=$HOME/include
LIBRARY_PATH=$HOME/lib
LD_LIBRARY_PATH=$HOME/lib
PKG_CONFIG_PATH=$HOME/lib/pkgconfig

export PATH C_INCLUDE_PATH LIBRARY_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH
