PATH="$HOME/bin:$PATH"
C_INCLUDE_PATH="$HOME/include:$C_INCLUDE_PATH"
LIBRARY_PATH="$HOME/lib:$LIBRARY_PATH"
LD_LIBRARY_PATH="$HOME/lib:$LD_LIBRARY_PATH"
PKG_CONFIG_PATH="$HOME/lib/pkgconfig:$PKG_CONFIG_PATH"
export PATH C_INCLUDE_PATH LIBRARY_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH
